// Quran Data — Surah metadata (114 Surahs)

class SurahInfo {
  final int number;
  final String name;
  final String arabicName;
  final int verseCount;
  final int startPage;
  final int juzz;
  final bool isMakki; // true = Makki, false = Madani

  const SurahInfo({
    required this.number,
    required this.name,
    required this.arabicName,
    required this.verseCount,
    required this.startPage,
    required this.juzz,
    required this.isMakki,
  });
}

const List<SurahInfo> kSurahs = [
  SurahInfo(number: 1,   name: 'Al-Fatihah',       arabicName: 'الفاتحة',        verseCount: 7,   startPage: 1,   juzz: 1,  isMakki: true),
  SurahInfo(number: 2,   name: 'Al-Baqarah',        arabicName: 'البقرة',         verseCount: 286, startPage: 2,   juzz: 1,  isMakki: false),
  SurahInfo(number: 3,   name: 'Aali-Imran',        arabicName: 'آل عمران',       verseCount: 200, startPage: 50,  juzz: 3,  isMakki: false),
  SurahInfo(number: 4,   name: 'An-Nisa',           arabicName: 'النساء',         verseCount: 176, startPage: 77,  juzz: 4,  isMakki: false),
  SurahInfo(number: 5,   name: 'Al-Maidah',         arabicName: 'المائدة',        verseCount: 120, startPage: 106, juzz: 6,  isMakki: false),
  SurahInfo(number: 6,   name: 'Al-Anam',           arabicName: 'الأنعام',        verseCount: 165, startPage: 128, juzz: 7,  isMakki: true),
  SurahInfo(number: 7,   name: 'Al-Araf',           arabicName: 'الأعراف',        verseCount: 206, startPage: 151, juzz: 8,  isMakki: true),
  SurahInfo(number: 8,   name: 'Al-Anfal',          arabicName: 'الأنفال',        verseCount: 75,  startPage: 177, juzz: 9,  isMakki: false),
  SurahInfo(number: 9,   name: 'At-Tawbah',         arabicName: 'التوبة',         verseCount: 129, startPage: 187, juzz: 10, isMakki: false),
  SurahInfo(number: 10,  name: 'Yunus',             arabicName: 'يونس',           verseCount: 109, startPage: 208, juzz: 11, isMakki: true),
  SurahInfo(number: 11,  name: 'Hud',               arabicName: 'هود',            verseCount: 123, startPage: 221, juzz: 11, isMakki: true),
  SurahInfo(number: 12,  name: 'Yusuf',             arabicName: 'يوسف',           verseCount: 111, startPage: 235, juzz: 12, isMakki: true),
  SurahInfo(number: 13,  name: 'Ar-Rad',            arabicName: 'الرعد',          verseCount: 43,  startPage: 249, juzz: 13, isMakki: false),
  SurahInfo(number: 14,  name: 'Ibrahim',           arabicName: 'إبراهيم',        verseCount: 52,  startPage: 255, juzz: 13, isMakki: true),
  SurahInfo(number: 15,  name: 'Al-Hijr',           arabicName: 'الحجر',          verseCount: 99,  startPage: 262, juzz: 14, isMakki: true),
  SurahInfo(number: 16,  name: 'An-Nahl',           arabicName: 'النحل',          verseCount: 128, startPage: 267, juzz: 14, isMakki: true),
  SurahInfo(number: 17,  name: 'Al-Isra',           arabicName: 'الإسراء',        verseCount: 111, startPage: 282, juzz: 15, isMakki: true),
  SurahInfo(number: 18,  name: 'Al-Kahf',           arabicName: 'الكهف',          verseCount: 110, startPage: 293, juzz: 15, isMakki: true),
  SurahInfo(number: 19,  name: 'Maryam',            arabicName: 'مريم',           verseCount: 98,  startPage: 305, juzz: 16, isMakki: true),
  SurahInfo(number: 20,  name: 'Ta-Ha',             arabicName: 'طه',             verseCount: 135, startPage: 312, juzz: 16, isMakki: true),
  SurahInfo(number: 21,  name: 'Al-Anbiya',         arabicName: 'الأنبياء',       verseCount: 112, startPage: 322, juzz: 17, isMakki: true),
  SurahInfo(number: 22,  name: 'Al-Hajj',           arabicName: 'الحج',           verseCount: 78,  startPage: 332, juzz: 17, isMakki: false),
  SurahInfo(number: 23,  name: 'Al-Muminun',        arabicName: 'المؤمنون',       verseCount: 118, startPage: 342, juzz: 18, isMakki: true),
  SurahInfo(number: 24,  name: 'An-Nur',            arabicName: 'النور',          verseCount: 64,  startPage: 350, juzz: 18, isMakki: false),
  SurahInfo(number: 25,  name: 'Al-Furqan',         arabicName: 'الفرقان',        verseCount: 77,  startPage: 359, juzz: 18, isMakki: true),
  SurahInfo(number: 26,  name: 'Ash-Shuara',        arabicName: 'الشعراء',        verseCount: 227, startPage: 367, juzz: 19, isMakki: true),
  SurahInfo(number: 27,  name: 'An-Naml',           arabicName: 'النمل',          verseCount: 93,  startPage: 377, juzz: 19, isMakki: true),
  SurahInfo(number: 28,  name: 'Al-Qasas',          arabicName: 'القصص',          verseCount: 88,  startPage: 385, juzz: 20, isMakki: true),
  SurahInfo(number: 29,  name: 'Al-Ankabut',        arabicName: 'العنكبوت',       verseCount: 69,  startPage: 396, juzz: 20, isMakki: true),
  SurahInfo(number: 30,  name: 'Ar-Rum',            arabicName: 'الروم',          verseCount: 60,  startPage: 404, juzz: 21, isMakki: true),
  SurahInfo(number: 31,  name: 'Luqman',            arabicName: 'لقمان',          verseCount: 34,  startPage: 411, juzz: 21, isMakki: true),
  SurahInfo(number: 32,  name: 'As-Sajdah',         arabicName: 'السجدة',         verseCount: 30,  startPage: 415, juzz: 21, isMakki: true),
  SurahInfo(number: 33,  name: 'Al-Ahzab',          arabicName: 'الأحزاب',        verseCount: 73,  startPage: 418, juzz: 21, isMakki: false),
  SurahInfo(number: 34,  name: 'Saba',              arabicName: 'سبأ',            verseCount: 54,  startPage: 428, juzz: 22, isMakki: true),
  SurahInfo(number: 35,  name: 'Fatir',             arabicName: 'فاطر',           verseCount: 45,  startPage: 434, juzz: 22, isMakki: true),
  SurahInfo(number: 36,  name: 'Ya-Sin',            arabicName: 'يس',             verseCount: 83,  startPage: 440, juzz: 22, isMakki: true),
  SurahInfo(number: 37,  name: 'As-Saffat',         arabicName: 'الصافات',        verseCount: 182, startPage: 446, juzz: 23, isMakki: true),
  SurahInfo(number: 38,  name: 'Sad',               arabicName: 'ص',              verseCount: 88,  startPage: 453, juzz: 23, isMakki: true),
  SurahInfo(number: 39,  name: 'Az-Zumar',          arabicName: 'الزمر',          verseCount: 75,  startPage: 458, juzz: 23, isMakki: true),
  SurahInfo(number: 40,  name: 'Ghafir',            arabicName: 'غافر',           verseCount: 85,  startPage: 467, juzz: 24, isMakki: true),
  SurahInfo(number: 41,  name: 'Fussilat',          arabicName: 'فصلت',           verseCount: 54,  startPage: 477, juzz: 24, isMakki: true),
  SurahInfo(number: 42,  name: 'Ash-Shura',         arabicName: 'الشورى',         verseCount: 53,  startPage: 483, juzz: 25, isMakki: true),
  SurahInfo(number: 43,  name: 'Az-Zukhruf',        arabicName: 'الزخرف',         verseCount: 89,  startPage: 489, juzz: 25, isMakki: true),
  SurahInfo(number: 44,  name: 'Ad-Dukhan',         arabicName: 'الدخان',         verseCount: 59,  startPage: 496, juzz: 25, isMakki: true),
  SurahInfo(number: 45,  name: 'Al-Jathiyah',       arabicName: 'الجاثية',        verseCount: 37,  startPage: 499, juzz: 25, isMakki: true),
  SurahInfo(number: 46,  name: 'Al-Ahqaf',          arabicName: 'الأحقاف',        verseCount: 35,  startPage: 502, juzz: 26, isMakki: true),
  SurahInfo(number: 47,  name: 'Muhammad',          arabicName: 'محمد',           verseCount: 38,  startPage: 507, juzz: 26, isMakki: false),
  SurahInfo(number: 48,  name: 'Al-Fath',           arabicName: 'الفتح',          verseCount: 29,  startPage: 511, juzz: 26, isMakki: false),
  SurahInfo(number: 49,  name: 'Al-Hujurat',        arabicName: 'الحجرات',        verseCount: 18,  startPage: 515, juzz: 26, isMakki: false),
  SurahInfo(number: 50,  name: 'Qaf',               arabicName: 'ق',              verseCount: 45,  startPage: 518, juzz: 26, isMakki: true),
  SurahInfo(number: 51,  name: 'Adh-Dhariyat',      arabicName: 'الذاريات',       verseCount: 60,  startPage: 520, juzz: 26, isMakki: true),
  SurahInfo(number: 52,  name: 'At-Tur',            arabicName: 'الطور',          verseCount: 49,  startPage: 523, juzz: 27, isMakki: true),
  SurahInfo(number: 53,  name: 'An-Najm',           arabicName: 'النجم',          verseCount: 62,  startPage: 526, juzz: 27, isMakki: true),
  SurahInfo(number: 54,  name: 'Al-Qamar',          arabicName: 'القمر',          verseCount: 55,  startPage: 528, juzz: 27, isMakki: true),
  SurahInfo(number: 55,  name: 'Ar-Rahman',         arabicName: 'الرحمن',         verseCount: 78,  startPage: 531, juzz: 27, isMakki: false),
  SurahInfo(number: 56,  name: 'Al-Waqiah',         arabicName: 'الواقعة',        verseCount: 96,  startPage: 534, juzz: 27, isMakki: true),
  SurahInfo(number: 57,  name: 'Al-Hadid',          arabicName: 'الحديد',         verseCount: 29,  startPage: 537, juzz: 27, isMakki: false),
  SurahInfo(number: 58,  name: 'Al-Mujadila',       arabicName: 'المجادلة',       verseCount: 22,  startPage: 542, juzz: 28, isMakki: false),
  SurahInfo(number: 59,  name: 'Al-Hashr',          arabicName: 'الحشر',          verseCount: 24,  startPage: 545, juzz: 28, isMakki: false),
  SurahInfo(number: 60,  name: 'Al-Mumtahanah',     arabicName: 'الممتحنة',       verseCount: 13,  startPage: 549, juzz: 28, isMakki: false),
  SurahInfo(number: 61,  name: 'As-Saf',            arabicName: 'الصف',           verseCount: 14,  startPage: 551, juzz: 28, isMakki: false),
  SurahInfo(number: 62,  name: 'Al-Jumuah',         arabicName: 'الجمعة',         verseCount: 11,  startPage: 553, juzz: 28, isMakki: false),
  SurahInfo(number: 63,  name: 'Al-Munafiqun',      arabicName: 'المنافقون',      verseCount: 11,  startPage: 554, juzz: 28, isMakki: false),
  SurahInfo(number: 64,  name: 'At-Taghabun',       arabicName: 'التغابن',        verseCount: 18,  startPage: 556, juzz: 28, isMakki: false),
  SurahInfo(number: 65,  name: 'At-Talaq',          arabicName: 'الطلاق',         verseCount: 12,  startPage: 558, juzz: 28, isMakki: false),
  SurahInfo(number: 66,  name: 'At-Tahrim',         arabicName: 'التحريم',        verseCount: 12,  startPage: 560, juzz: 28, isMakki: false),
  SurahInfo(number: 67,  name: 'Al-Mulk',           arabicName: 'الملك',          verseCount: 30,  startPage: 562, juzz: 29, isMakki: true),
  SurahInfo(number: 68,  name: 'Al-Qalam',          arabicName: 'القلم',          verseCount: 52,  startPage: 564, juzz: 29, isMakki: true),
  SurahInfo(number: 69,  name: 'Al-Haqqah',         arabicName: 'الحاقة',         verseCount: 52,  startPage: 566, juzz: 29, isMakki: true),
  SurahInfo(number: 70,  name: 'Al-Maarij',         arabicName: 'المعارج',        verseCount: 44,  startPage: 568, juzz: 29, isMakki: true),
  SurahInfo(number: 71,  name: 'Nuh',               arabicName: 'نوح',            verseCount: 28,  startPage: 570, juzz: 29, isMakki: true),
  SurahInfo(number: 72,  name: 'Al-Jinn',           arabicName: 'الجن',           verseCount: 28,  startPage: 572, juzz: 29, isMakki: true),
  SurahInfo(number: 73,  name: 'Al-Muzzammil',      arabicName: 'المزمل',         verseCount: 20,  startPage: 574, juzz: 29, isMakki: true),
  SurahInfo(number: 74,  name: 'Al-Muddaththir',    arabicName: 'المدثر',         verseCount: 56,  startPage: 575, juzz: 29, isMakki: true),
  SurahInfo(number: 75,  name: 'Al-Qiyamah',        arabicName: 'القيامة',        verseCount: 40,  startPage: 577, juzz: 29, isMakki: true),
  SurahInfo(number: 76,  name: 'Al-Insan',          arabicName: 'الإنسان',        verseCount: 31,  startPage: 578, juzz: 29, isMakki: false),
  SurahInfo(number: 77,  name: 'Al-Mursalat',       arabicName: 'المرسلات',       verseCount: 50,  startPage: 580, juzz: 29, isMakki: true),
  SurahInfo(number: 78,  name: 'An-Naba',           arabicName: 'النبأ',          verseCount: 40,  startPage: 582, juzz: 30, isMakki: true),
  SurahInfo(number: 79,  name: 'An-Naziat',         arabicName: 'النازعات',       verseCount: 46,  startPage: 583, juzz: 30, isMakki: true),
  SurahInfo(number: 80,  name: 'Abasa',             arabicName: 'عبس',            verseCount: 42,  startPage: 585, juzz: 30, isMakki: true),
  SurahInfo(number: 81,  name: 'At-Takwir',         arabicName: 'التكوير',        verseCount: 29,  startPage: 586, juzz: 30, isMakki: true),
  SurahInfo(number: 82,  name: 'Al-Infitar',        arabicName: 'الانفطار',       verseCount: 19,  startPage: 587, juzz: 30, isMakki: true),
  SurahInfo(number: 83,  name: 'Al-Mutaffifin',     arabicName: 'المطففين',       verseCount: 36,  startPage: 587, juzz: 30, isMakki: true),
  SurahInfo(number: 84,  name: 'Al-Inshiqaq',       arabicName: 'الانشقاق',       verseCount: 25,  startPage: 589, juzz: 30, isMakki: true),
  SurahInfo(number: 85,  name: 'Al-Buruj',          arabicName: 'البروج',         verseCount: 22,  startPage: 590, juzz: 30, isMakki: true),
  SurahInfo(number: 86,  name: 'At-Tariq',          arabicName: 'الطارق',         verseCount: 17,  startPage: 591, juzz: 30, isMakki: true),
  SurahInfo(number: 87,  name: 'Al-Ala',            arabicName: 'الأعلى',         verseCount: 19,  startPage: 591, juzz: 30, isMakki: true),
  SurahInfo(number: 88,  name: 'Al-Ghashiyah',      arabicName: 'الغاشية',        verseCount: 26,  startPage: 592, juzz: 30, isMakki: true),
  SurahInfo(number: 89,  name: 'Al-Fajr',           arabicName: 'الفجر',          verseCount: 30,  startPage: 593, juzz: 30, isMakki: true),
  SurahInfo(number: 90,  name: 'Al-Balad',          arabicName: 'البلد',          verseCount: 20,  startPage: 594, juzz: 30, isMakki: true),
  SurahInfo(number: 91,  name: 'Ash-Shams',         arabicName: 'الشمس',          verseCount: 15,  startPage: 595, juzz: 30, isMakki: true),
  SurahInfo(number: 92,  name: 'Al-Layl',           arabicName: 'الليل',          verseCount: 21,  startPage: 595, juzz: 30, isMakki: true),
  SurahInfo(number: 93,  name: 'Ad-Duhaa',          arabicName: 'الضحى',          verseCount: 11,  startPage: 596, juzz: 30, isMakki: true),
  SurahInfo(number: 94,  name: 'Ash-Sharh',         arabicName: 'الشرح',          verseCount: 8,   startPage: 596, juzz: 30, isMakki: true),
  SurahInfo(number: 95,  name: 'At-Tin',            arabicName: 'التين',          verseCount: 8,   startPage: 597, juzz: 30, isMakki: true),
  SurahInfo(number: 96,  name: 'Al-Alaq',           arabicName: 'العلق',          verseCount: 19,  startPage: 597, juzz: 30, isMakki: true),
  SurahInfo(number: 97,  name: 'Al-Qadr',           arabicName: 'القدر',          verseCount: 5,   startPage: 598, juzz: 30, isMakki: true),
  SurahInfo(number: 98,  name: 'Al-Bayyinah',       arabicName: 'البينة',         verseCount: 8,   startPage: 598, juzz: 30, isMakki: false),
  SurahInfo(number: 99,  name: 'Az-Zalzalah',       arabicName: 'الزلزلة',        verseCount: 8,   startPage: 599, juzz: 30, isMakki: false),
  SurahInfo(number: 100, name: 'Al-Adiyat',         arabicName: 'العاديات',       verseCount: 11,  startPage: 599, juzz: 30, isMakki: true),
  SurahInfo(number: 101, name: 'Al-Qariah',         arabicName: 'القارعة',        verseCount: 11,  startPage: 600, juzz: 30, isMakki: true),
  SurahInfo(number: 102, name: 'At-Takathur',       arabicName: 'التكاثر',        verseCount: 8,   startPage: 600, juzz: 30, isMakki: true),
  SurahInfo(number: 103, name: 'Al-Asr',            arabicName: 'العصر',          verseCount: 3,   startPage: 601, juzz: 30, isMakki: true),
  SurahInfo(number: 104, name: 'Al-Humazah',        arabicName: 'الهمزة',         verseCount: 9,   startPage: 601, juzz: 30, isMakki: true),
  SurahInfo(number: 105, name: 'Al-Fil',            arabicName: 'الفيل',          verseCount: 5,   startPage: 601, juzz: 30, isMakki: true),
  SurahInfo(number: 106, name: 'Quraysh',           arabicName: 'قريش',           verseCount: 4,   startPage: 602, juzz: 30, isMakki: true),
  SurahInfo(number: 107, name: 'Al-Maun',           arabicName: 'الماعون',        verseCount: 7,   startPage: 602, juzz: 30, isMakki: true),
  SurahInfo(number: 108, name: 'Al-Kawthar',        arabicName: 'الكوثر',         verseCount: 3,   startPage: 602, juzz: 30, isMakki: true),
  SurahInfo(number: 109, name: 'Al-Kafirun',        arabicName: 'الكافرون',       verseCount: 6,   startPage: 603, juzz: 30, isMakki: true),
  SurahInfo(number: 110, name: 'An-Nasr',           arabicName: 'النصر',          verseCount: 3,   startPage: 603, juzz: 30, isMakki: false),
  SurahInfo(number: 111, name: 'Al-Masad',          arabicName: 'المسد',          verseCount: 5,   startPage: 603, juzz: 30, isMakki: true),
  SurahInfo(number: 112, name: 'Al-Ikhlas',         arabicName: 'الإخلاص',        verseCount: 4,   startPage: 604, juzz: 30, isMakki: true),
  SurahInfo(number: 113, name: 'Al-Falaq',          arabicName: 'الفلق',          verseCount: 5,   startPage: 604, juzz: 30, isMakki: true),
  SurahInfo(number: 114, name: 'An-Nas',            arabicName: 'الناس',          verseCount: 6,   startPage: 604, juzz: 30, isMakki: true),
];
